### Create a new Category (Skincare)
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
  "name": "Skincare",
  "imageUrl": "https://example.com/skincare.jpg"
}

### Create another Category (Make Up)
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
  "name": "Make Up",
  "imageUrl": "https://example.com/makeup.jpg"
}